---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: observability-single-span-pipeline
  namespace: observability-single-span
  labels:
    app.kubernetes.io/part-of: observability-single-span
    app.kubernetes.io/component: tekton-pipeline
