---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: observability-demo-pipeline
  namespace: observability-demo
  labels:
    app.kubernetes.io/part-of: observability-demo
    app.kubernetes.io/component: tekton-pipeline
