apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: demo-monolith
  namespace: observability-demo
  labels:
    app.kubernetes.io/name: demo-monolith
    app.kubernetes.io/part-of: observability-demo
spec:
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/sawoohoorun/ocp-observ-monolithic.git
      ref: main
    contextDir: observability-demo-ocp418/spring-monolith
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: demo-monolith:1.0.0
  triggers:
    - type: ConfigChange
