server:
  port: 8080

spring:
  application:
    name: order-demo-app
  thymeleaf:
    cache: false

demo:
  backend-base-url: http://backend-app.observability-single-span.svc.cluster.local:8080

management:
  opentelemetry:
    resource-attributes:
      service.name: order-demo-app
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://otel-collector.observability-single-span.svc.cluster.local:4318/v1/traces
