apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: demo
  namespace: observability-single-span
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/part-of: observability-single-span
spec:
  managementState: Managed
  storage:
    traces:
      backend: memory
      size: 2Gi
  jaegerui:
    enabled: true
    route:
      enabled: true
  extraConfig:
    tempo:
      compactor:
        compaction:
          block_retention: 24h
