apiVersion: v1
kind: Service
metadata:
  name: frontend-ui
  namespace: dev
  labels:
    app.kubernetes.io/name: frontend-ui
    app.kubernetes.io/part-of: dev
spec:
  selector:
    app.kubernetes.io/name: frontend-ui
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP
